### ISSUE TITLE
utilise date_inscription

### ISSUE THREAD

**Issue by JamesRezo** [geodiversite/geodiversite_monolithe#34]
https://github.com/geodiversite/geodiversite/blob/5f8e7266fdddd4c7cfc137f2e90455f93e6bc207/geodiversite/paquet.xml#L44 dit qu'il "utilise" date_inscription, mais dans le shell d'installation et le "metaplugin" on a un "necessite" et une install dans plugins-dist

et on trouve, par exemple le critère {!par date_inscription} dans https://github.com/geodiversite/geodiversite/blob/c55507ad86e4558893c39e594f83af6f4818e484/geodiversite/extra1/auteurs.html#L6

du coup : utilise ou necessite ?

**Comment by brunob** [comment]
nécessite ;)
